services:
  backend:
    build: ./healthcare_backend
    container_name: healthcare_backend
    command: >
      sh -c "sleep 10 &&
             python manage.py makemigrations --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./healthcare_backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./healthcare_backend/.env
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    networks:
      - healthcare-network

  frontend:
    build:
      context: ./healthcare-frontend/NeuroMed-2f
      dockerfile: Dockerfile
    container_name: healthcare_frontend
    working_dir: /app
    volumes:
      - ./healthcare-frontend/NeuroMed-2f:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - healthcare-network

  db:
    image: postgres:16
    container_name: healthcare_db
    environment:
      POSTGRES_DB: healthcare_db
      POSTGRES_USER: aditya
      POSTGRES_PASSWORD: aditya123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - healthcare-network

volumes:
  postgres_data:

networks:
  healthcare-network:
    driver: bridge

